version: '3.8'

services:
  # node-app:
  #   build: .
  #   ports:
  #     - "8888:8888"
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   environment:
  #     - DB_HOST=db
  #     - DB_USER=root
  #     - DB_PASSWORD=example
  #     - DB_NAME=EvaluationSheet

  db:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: EvaluationSheet
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    restart: always
    ports:
      - "80:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: example
    volumes:
      - ./php-config/php.ini:/usr/local/etc/php/php.ini

volumes:
  db_data:

  # ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'example';
# FLUSH PRIVILEGES;

