version: '3.8'
services:
  # node-app:
  #   build: .
  #   ports:
  #     - "8888:8888"
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   environment:
  #     - DB_HOST=db
  #     - DB_USER=root
  #     - DB_PASSWORD=example
  #     - DB_NAME=EvaluationSheet
  db:
    image: mysql:5.7
    container_name: db-container
    ports:
      - "6959:3306"
    environment:
      MYSQL_DATABASE: 'Greeting'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - db-data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    ports:
      - "6960:80"
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: password
    depends_on:
      - db

    
          
            
    

          
          Expand Down
    
    
  
volumes:
  db_data:
  # ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'example';
# FLUSH PRIVILEGES;