version: '3.8'
services:
  node-app:
    build: .
    ports:
      - "80:80"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=Depa@1234
      - DB_NAME=EvaluationSheet
    volumes:
      - .:/usr/src/app

  # db:
  #   image: mysql:5.7
  #   platform: linux/amd64
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: Depa@1234
  #     MYSQL_DATABASE: EvaluationSheet
  #     MYSQL_INITDB_SKIP_TZINFO: 1
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   healthcheck:
  #     test: ["CMD-SHELL", "mysqladmin ping -h localhost || exit 1"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3
  #   command: mysqld --innodb-force-recovery=1

volumes:
  db_data: